---
- hosts: all
  tasks:
  - name: i want to ping
    ping:

  - name: i want to install "apache2"
    apt:
     name: "apache2"
     state: present

  - name: i want to start a webserver
    service: "apache2"
    state: present
  
  - name: i want to install git 
    apt:
     name: git
     state: present